# Your project's server will run on localhost:xxxx at this port
PORT: 8000

# Autoprefixer will make sure your CSS works with these browsers
BROWSERS:
  - "last 2 versions"
  - "ie >= 9"
  - "ios >= 7"

# Gulp will reference these paths when it copies files
PATHS:
  # Paths to images
  icons: "assets/img/svg-icons/"

  # Paths to Sass libraries, which can then be loaded with @import
  sass:
    - "node_modules/foundation-sites/scss"
    - "node_modules/motion-ui/src"

  # Paths to JavaScript libraries, which are combined into one file
  javascript:
    # Libraries required by Foundation
    - "node_modules/what-input/dist/what-input.js"

    # Core Foundation files
    - "node_modules/foundation-sites/js/foundation.core.js"
    - "node_modules/foundation-sites/js/foundation.util.*.js"

    # Individual Foundation components
    # If you aren't using a component, just remove it from the list
    - "node_modules/foundation-sites/js/foundation.abide.js"
    - "node_modules/foundation-sites/js/foundation.accordion.js"
    - "node_modules/foundation-sites/js/foundation.accordionMenu.js"
    - "node_modules/foundation-sites/js/foundation.drilldown.js"
    - "node_modules/foundation-sites/js/foundation.dropdown.js"
    - "node_modules/foundation-sites/js/foundation.dropdownMenu.js"
    - "node_modules/foundation-sites/js/foundation.equalizer.js"
    - "node_modules/foundation-sites/js/foundation.interchange.js"
    - "node_modules/foundation-sites/js/foundation.magellan.js"
    - "node_modules/foundation-sites/js/foundation.offcanvas.js"
    - "node_modules/foundation-sites/js/foundation.orbit.js"
    - "node_modules/foundation-sites/js/foundation.responsiveMenu.js"
    - "node_modules/foundation-sites/js/foundation.responsiveToggle.js"
    - "node_modules/foundation-sites/js/foundation.reveal.js"
    - "node_modules/foundation-sites/js/foundation.slider.js"
    - "node_modules/foundation-sites/js/foundation.sticky.js"
    - "node_modules/foundation-sites/js/foundation.tabs.js"
    - "node_modules/foundation-sites/js/foundation.toggler.js"
    - "node_modules/foundation-sites/js/foundation.tooltip.js"
    - "node_modules/foundation-sites/js/foundation.zf.responsiveAccordionTabs.js"

    # Paths to your custom JS are here
    - "assets/js/vendor/*.js"
    - "assets/js/theme/theme.js"

# Used in the theme .pot file for translation 
POT:
  domain: 'croft'
  package: 'croft'
  bugReport: "https://github.com/brettsmason/croft/issues"
  lastTranslator: "Brett Mason <brettsmason@gmail.com>"
  team: "Brett Mason <brettsmason@gmail.com>"


# Theme strings. Used in the `renametheme` gulp task.
THEME:
  ## The current strings in the theme
  CURRENT:
    name: "Croft",
    slug: "croft",
    prefix: "croft_"
  ## The strings to rename in the theme
  NEW:
    name: "Croft",
    slug: "croft",
    prefix: "croft_"